kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: opencart
spec:
  host: opencart.apps.cluster-4ntr9.4ntr9.sandbox1425.opentlc.com
  to:
    kind: Service
    name: opencart
    weight: 100
  port:
    targetPort: http
