apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: opencart
  includeCRDs: false
  valuesInline:
    opencartHost: opencart.apps.cluster-4ntr9.4ntr9.sandbox1425.opentlc.com
    opencartPassword: user
    mariadb:
      auth:
        rootPassword: root
        password: opencart
    updateStrategy:
      type: Recreate
  releaseName: opencart
  version: 12.3.1
  repo: https://charts.bitnami.com/bitnami

resources:
- base/route.yaml

namespace: opencart

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: StatefulSet
    name: opencart-mariadb
  patch: |-
    - op: remove
      path: /spec/template/spec/securityContext
    - op: remove
      path: /spec/template/spec/containers/0/securityContext
- target:
    group: apps
    version: v1
    kind: Deployment
    name: opencart
  patch: |-
    - op: remove
      path: /spec/template/spec/securityContext
    - op: remove
      path: /spec/template/spec/containers/0/securityContext
